/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacoes;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import pagamentos.model.Cliente;

/**
 *
 * @author root
 */
public class Gastos extends javax.swing.JPanel {

    /**
     * Creates new form Gastos
     */
    Cliente u;
    public Gastos(Cliente u) {
        initComponents();
        this.u = u;
        grafico();
    }
    public void grafico() {
     
        try {

            String myDriver = "com.mysql.jdbc.Driver";
            String myUrl = "jdbc:mysql://127.0.0.1/db";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "tallys", "teste");

            //String search = "SELECT * FROM Cliente WHERE User='" + beneficiarioField.getText() + "'";
            String search = "SELECT ValorTransacao FROM Transacao NATURAL JOIN Cliente_tem_Transacao WHERE Cliente_tem_Transacao.Id_Cliente='" + u.getIdCliente() + "'";

            Statement st = (Statement) conn.createStatement();

            ResultSet rs = st.executeQuery(search);
            
            DefaultCategoryDataset ds = new DefaultCategoryDataset();
            ArrayList<Double> saldoList = new ArrayList<Double>();
            while (rs.next()) {
                System.out.println(rs.getDouble("ValorTransacao"));
                saldoList.add(rs.getDouble("ValorTransacao"));

            }

            String search2 = "SELECT DataTransacao FROM Transacao NATURAL JOIN Cliente_tem_Transacao WHERE Cliente_tem_Transacao.Id_Cliente='" + u.getIdCliente() + "'";
            Statement st2 = conn.createStatement();
            ResultSet rs2 = st2.executeQuery(search2);
            
            
            ArrayList<String> dataList = new ArrayList<String>();
            while (rs2.next()) {
                System.out.println(rs2.getString("DataTransacao"));                
                dataList.add(rs2.getString("DataTransacao"));
            }
            
            for (int i = 0; i < saldoList.size(); i++) {
                ds.addValue(saldoList.get(i), "Máximo", dataList.get(i));
            }

            JFreeChart grafico = ChartFactory.createLineChart("Meu Grafico", "Dia", "Valor", ds, PlotOrientation.VERTICAL, true,true,false);
            OutputStream arquivo = new FileOutputStream("grafico.png");
            ChartUtilities.writeChartAsPNG(arquivo, grafico, 550, 400);
            arquivo.close();

        } catch (SQLException ex) {
            Logger.getLogger(Gastos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gastos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Gastos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
